### ISSUE TITLE
Header for childview holder

### ISSUE THREAD

**Issue by wishygupta** [Xigong93/ExpandableRecyclerView#35]
Is it possible we can add a header view to child view holder as well?

**Comment by Xigong93** [comment]
Do you have any sketch? I can't image what it will look like.

**Comment by wishygupta** [comment]
Something like this image
<img width="442" alt="Screenshot 2021-11-03 at 3 17 04 PM" src="https://user-images.githubusercontent.com/9713225/140039100-a8bdd3f2-4bf0-4354-bca2-2006a91a27fa.png">
Indivdual section - this is header view which will expand
Property Section - this will be header view for expanded layout
Then finally the expanded remaining data

Closed will look like 
<img width="425" alt="Screenshot 2021-11-03 at 3 20 49 PM" src="https://user-images.githubusercontent.com/9713225/140039393-1033ddaf-6697-4baf-8b96-f40bde52d3fb.png">

**Comment by Xigong93** [comment]
Sorry ,maybe I am late. I try to achieve what you describe. Code on branch `child-sticky-header`. You can take a look. It's just a demo for learn ,don't put it on business project.

**Comment by Xigong93** [comment]
https://user-images.githubusercontent.com/17515825/141247007-3c787fe6-be7f-447f-b9b4-6c14b3249681.mp4

**Comment by wishy-viewlift** [comment]
Thanks
I can do a workaround on it and make it compatible for my need.
