### ISSUE TITLE
吸顶的时候，调用notifyDataSetChanged，吸顶布局会发生闪烁

### ISSUE THREAD

**Issue by hyx0804xiaokeai** [Xigong93/ExpandableRecyclerView#36]

**Comment by Xigong93** [comment]
我复现了，正在尝试修复一下

**Comment by Xigong93** [comment]
在v0.8.9 版本已经修复了这个问题，请再试一下。

**Comment by 404N** [comment]
> 在v0.8.9 版本已经修复了这个问题，请再试一下。

为什么0.8.9版本依赖引入失败啊

**Comment by Xigong93** [comment]
![2EBFE63A](https://user-images.githubusercontent.com/17515825/143170243-3fe8735d-89f6-4da1-bfb5-51bf1baa8a98.jpg)
是JitPack 需要配置一下才能支持gradle 7.0.我已经改过了，在v0.9.0版本
