### ISSUE TITLE
V0.9.0,吸顶布局

### ISSUE THREAD

**Issue by 404N** [Xigong93/ExpandableRecyclerView#38]
在0.9.0版本调用notifyDataSetChanged()方法后，顶部布局不会闪烁了，但是也不会刷新了。。。我想点击顶部展开的时候顶部能够有变化，比如箭头的指向，但是展开列表时吸顶布局并没有发生变化

**Comment by 404N** [comment]
要变化的话现在就只能使用
notifyDataSetChanged()
notifyGroupChange()
两个方法来刷新顶部布局。。。。

**Comment by Xigong93** [comment]
你好，v0.9.2 已经修复了这个问题。感谢支持

**Comment by 404N** [comment]
> 你好，v0.9.2 已经修复了这个问题。感谢支持

好的，辛苦了
